apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-argo
spec:
  selector:
    matchLabels:
      app: application-argo
  replicas: 2
  template:
    metadata:
      labels:
        app: application-argo
    spec:
      containers:
      - name: test-app
        image: dockerhublab/test-app:7.0
        ports:
        - containerPort: 5000
