apiVersion: v1
kind: Service
metadata:
  name: application-argo-corso
spec:
  selector:
    app: application-argo
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32001
